all: compile link

compile:
	g++ -I src/include -I src/include/* -I include -c main.cpp Asteroid.cpp Player.cpp NEWgame.cpp interpreter.cpp init.cpp Weapon.cpp Entity.cpp PlayerController.cpp
link:
	g++ main.o -o main -L src/lib -L . -l sfml-graphics -l sfml-window -l sfml-system -l sfml-audio -l lua -l tgui -static-libgcc -static-libstdc++
